name: Update operating hours

on:
  schedule:
    - cron:  '0 16 * * *'

jobs:
  updateHours:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the updating script
      run: python updater.py
      shell: bash
      working-directory: ./do-not-touch
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git commit -m "Automated update of operating hours" -a || echo "Nothing to update"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Request Github Pages build job
      run: >-
        curl -L -X POST 
        -H "Content-Type: application/json"
        -H "Authorization: token ${{ secrets.ACTIONS_PAT }}"
        "https://api.github.com/repos/${{ github.repository }}/pages/builds"
